CC=g++
FLAGS=-O2 -DNDEBUG -Wall -std=gnu++0x -fdata-sections -ffunction-sections -Wl,--gc-sections
FILES=lib/etana/*.cpp lib/fsc/*.cpp etsplit_compounds.cpp
LIBS=-pthread

all:
	$(CC) $(FLAGS) -o et_split_compounds $(FILES) $(LIBS)
